### ISSUE TITLE
Un-watch and reinitialize file when lstat returns not found

### ISSUE THREAD

**Issue by troy** [papertrail/remote_syslog2#32] opened 2014-09-19 16:12 UTC
If rs2 is watching a specific path (not a wildcard) and the file is removed, at least in 

```
Linux hostname-removed 3.15.8+ #2 SMP Fri Aug 15 22:29:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

.. as a Docker container, rs2 will immediately be notified and do an `lstat`:

```
[pid  1747] lstat("/var/log/blah/abc.log",  <unfinished ...>
[pid  1743] clock_gettime(CLOCK_REALTIME, {1411142701, 595898285}) = 0
[pid  1747] <... lstat resumed> 0xc210221240) = -1 ENOENT (No such file or directory)
```

If that `abc.log` is recreated, all subsequent writes to that file are ignored, even though rs2 could have detected that it was briefly not present.

**Comment by leonsodhi** [comment] 2015-03-11 01:30
Just to add to that, it seems as though r_s2 does detect a file being moved but ignores deletions. This also happens when using a wildcard.

**Comment by snorecone** [comment] 2016-11-23 18:15
Closing this since I've confirmed that this is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)

**Closed by snorecone** 2016-11-23 18:15 UTC
