### ISSUE TITLE
Detect changes to watched symlinks

### ISSUE THREAD

**Issue by leonsodhi** [papertrail/remote_syslog2#45] opened 2014-10-15 22:52 UTC
Remote_syslog stops tracking a file if the directory or file that it's monitoring is a symlink that changes.

**Comment by windelicato** [comment] 2015-01-09 17:54
:+1: Currently I need to restart remote_syslog whenever I deploy. This is something I miss from the previous version

**Comment by troy** [comment] 2015-01-09 18:39
Thanks, gentlemen. Noted and on our radar (and patches accepted, of course).

**Comment by troy** [comment] 2015-01-09 18:58
@TheChuckster @windelicato question for you: are you pointing remote_syslog to a specific path to the symlink, or to a glob?

Using a glob makes remote_syslog recheck that path every `--new-file-check-interval` seconds, which defaults to 10. This may make it detect the change, though I'm not sure; the file may need to not exist for one interval first. If either of you happen to have data points from your environments, I'd welcome them.

**Comment by windelicato** [comment] 2015-01-09 21:31
@troy I'm pointing it at a glob using something like `/srv/www/*/current/var/logs/production.log`. It picks up the correct file at startup, but when `current/` links to a new directory, it fails to pick up the change after any period of time

**Comment by TheChuckster** [comment] 2015-01-09 21:44
@troy It seems like all you need to do is add a handler for inotify IN_MOVE_SELF events to inotify.go (might even have to go upstream to fsnotify to do this).

@windelicato This might be a different problem all together. I'm not sure what inotify's behavior looks like in this case (maybe it's the same thing as if a mount point changes?).

**Comment by troy** [comment] 2015-01-11 04:47
@TheChuckster Thanks for digging in here. Any chance you have a source (or personal knowledge) that IN_MOVE_SELF is delivered when a symlink is re-linked or removed and re-added? We'll try to repro it with strace before implementing a handler, of course, I'm just wondering if you happened to find a description of the behavior. inotify's manpage doesn't describe symlinks specifically.

**Comment by troy** [comment] 2015-01-11 04:48
@windelicato thanks, that gives us one specific case to work with (even if it's different than @TheChuckster's, as it may well be).

**Comment by soultech67** [comment] 2016-01-12 18:26
I am encountering what might be a similar issue. My config points directly to a file location /opt/app/logs/symlinktologfile links to /opt/app/logs/somelog. When logrotate.d rotates somelog it appears that remote_syslog stops sending any new messages to the server. I have to restart remote_syslog to get messages sent.

**Comment by waits** [comment] 2016-04-15 18:20
I see this is quite old, but it's causing problems for me as well. I'm willing to work on it if you guys still want this fixed.

**Comment by emwalker** [comment] 2016-11-19 23:13
+1

**Comment by snorecone** [comment] 2016-11-23 18:30
I'm closing this since I've confirmed that this is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19).

**Closed by snorecone** 2016-11-23 18:30 UTC
