### ISSUE TITLE
Release inotify instances (and other resources) for files when they disappear

### ISSUE THREAD

**Issue by leonsodhi** [papertrail/remote_syslog2#70] opened 2015-06-13 00:07 UTC
If a file is moved or deleted, remote_syslog2 will wait for it to return and then continue monitoring for changes. In cases where new log files are generated on a regular basis and old ones are moved out to another directory for archival purposes, a resource leak will occur.

**Comment by snorecone** [comment] 2016-11-23 18:44
Closing this since I've confirmed that this is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)

**Closed by snorecone** 2016-11-23 18:44 UTC
