### ISSUE TITLE
remote_syslog is rendered non operational on overlayfs

### ISSUE THREAD

**Issue by danielschonfeld** [papertrail/remote_syslog2#59] opened 2015-03-07 21:33 UTC
Our company uses docker with the overlayfs storage driver (the latest CoreOS images are like that) and since inotify isn't implemented in overlayfs remote_syslog is rendered non operational on such containers.

It appears that PR #35 solves this issue.  If it could just be integrated into RS2.

**Comment by troy** [comment] 2015-03-07 23:56
That's almost certainly the cause. Given that, and since overlayfs's lack of inotify is a known issue ([details](https://www.google.com/search?q=overlayfs+inotify), I'm going to close this issue and continue the discussion on the PR.

**Closed by troy** 2015-03-07 23:56 UTC
