### ISSUE TITLE
Doesn't monitor files that didn't exist when the process started, but were added later

### ISSUE THREAD

**Issue by gopi-ar** [papertrail/remote_syslog2#9] opened 2014-05-20 04:42 UTC
Suppose the `yml` file has a log path: `/var/www/error.log` that doesn't exist when `remote_syslog` starts.  Assume this was because the server was freshly installed, log rotated, etc. Now even if that log file is created shortly afterwards, `remote_syslog` won't monitor this until it has been restarted (`service remote_syslog restart`).

This is difficult to execute on large clusters/nodes where files may not exist, but may be added later.

**Comment by troy** [comment] 2015-01-09 19:12
Just documenting for anyone else who comes across this issue: this is already supported and handled by using a glob. That is, remote_syslog will periodically recheck `/some/path/*.log` (or even `/some/path/error.log*`).

The behavior in this issue only applies when a wildcard is not used, such as `/some/path/error.log`.

**Comment by snorecone** [comment] 2016-11-23 17:52
Closing this since I've confirmed that this is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)

**Closed by snorecone** 2016-11-23 17:52 UTC
