### ISSUE TITLE
Option to retry on failure when using TCP

### ISSUE THREAD

**Issue by bradvido** [papertrail/remote_syslog2#108] opened 2015-11-23 19:43 UTC
For the use-case where we want to guarantee that we don't lose logs lines, it would be nice to have the TCP protocol have an option to "retry-after" some time interval when it detects that  the message failed to be sent to the remote machine.

Right now, this error occurs and the log line is lost:

```
ERROR  remote_syslog.go:124 Syslog error: dial tcp <ipadress>:514: ConnectEx tcp: No connection could be made because the target machine actively refused it.
```

 Obviously this wouldn't make sense for UDP.

**Comment by johlym** [comment] 2016-06-01 18:51
Hmm. An active refusal is a different behavior than just not answering `SYN` packets. The latter should, by the TCP standard, trigger a retry whereas a blatant `no, I will not allow connections` is pretty obvious from a TCP perspective that a connection isn't going to happen and thus not much point in retrying, no?

**Comment by troy** [comment] 2016-06-02 04:23
I think even the explicit reply case is debatable. If the server sends back an ICMP port unreachable indicating that the host (well, destination IP) was reached but nothing is bound on the port, I could see an argument against retrying. Most other explicit responses - ICMP host unreachable, network unreachable, administratively prohibited, etc - could easily be transient errors, though, and even port unreachable might be because a daemon crashed.

So, I think I lean towards retrying even in explicit cases, though not aggressively.

**Comment by snorecone** [comment] 2016-11-23 19:05
Closing this since I've confirmed `tcp` connection retry is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)

**Closed by snorecone** 2016-11-23 19:05 UTC
