### ISSUE TITLE
Display usage or print an error msg when random parameters are passed to the executable

### ISSUE THREAD

**Issue by leonsodhi** [papertrail/remote_syslog2#23] opened 2014-08-15 01:06 UTC
```
remote_syslog not_valid
```

should display the usage info or return an error

**Comment by featalion** [comment] 2015-06-18 01:08
@leonsodhi currently, when unknown flag is passed to executable, it prints usage message.
All arguments, even when they interleave with flags, are treated as files to watch and merged with list of files from config. Seems outdated, already resolved, or... I did not get it.

**Comment by leonsodhi** [comment] 2015-06-18 18:16
@featalion good catch, and I didn't consider this properly when I raised it. The problem is that users are executing `remote_syslog restart` thinking that it will restart the service, but as you mentioned,  `restart` is interpreted as a file instead.

Stealing an idea from @troy, perhaps we could print something to stdout if r_s2 can't find a non-glob file path when it starts, even if it's being daemonized. In the example above, it might print something like "Can't monitor restart". Would that work? 

Also, other ideas/solutions are very welcome here if you have them :-)

**Comment by featalion** [comment] 2015-06-18 18:42
In this case `remote_syslog2` behave exactly how you want. If file does not exist, it prints something like:
`{TIME} ERROR  remote_syslog.go:81 Cannot forward restart, it may not exist`

**Comment by snorecone** [comment] 2016-11-23 17:56
Closing this since `remote_syslog2` will print usage with invalid flags, and print a warning in the log if a file like `restart` doesn't exist. Confirmed in the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)

**Closed by snorecone** 2016-11-23 17:56 UTC
