### ISSUE TITLE
The timestamp and timezone are different for some kinds of log lines

### ISSUE THREAD

**Issue by librato-peter** [papertrail/remote_syslog2#142] opened 2016-04-25 19:06 UTC
```
2016/04/24 07:02:31 Seeked /path/to/file.log - &{Offset:0 Whence:2}
2016-04-24 14:02:41 DEBUG  remote_syslog.go:72 Evaluating file globs
```

**Comment by johlym** [comment] 2016-05-31 22:15
Took a look at this. 

The first message's timestamp is generated from [the default go logging library](https://golang.org/src/log/log.go) by way of [`hpcloud/tail`](https://github.com/hpcloud/tail/blob/fff2f2d9e03958ee916ed469d7983be66aa4eb07/util/util.go#L17) which uses forward slashes, while the second line, generated by us via [`howbazzar/loggo`](https://github.com/howbazaar/loggo/blob/d2fb76909109d51bf42f3671abdee01104dac83f/logger.go#L358), relies on the go [`Time`](https://golang.org/src/time/time.go?s=22856:22871#L771) function directly (and leaves the output it as is), in a more proper unix-y format.

Short of getting hpcloud to start using a different logging library (or vice versa with loggo), not sure if we can do much about this sans forking and maintaining our own variant of either.

Let me know what you think @librato-peter

**Comment by johlym** [comment] 2016-05-31 22:23
@collinvandyck, you're a Go expert. Thoughts?

**Comment by collinvandyck** [comment] 2016-05-31 22:33
one's proficiency with golang probably has little to do with this. it is seemingly just a generic issue with a 3rd party lib not doing what you want.  probably just fork it and modify and keep up with upstream changes? sorry, this sounds really annoying to deal with. bonus points for submitting a PR to the lib and getting it merged in etc.

**Comment by snorecone** [comment] 2016-11-23 19:19
Closing this since I've confirmed that this is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)

`hpcloud/tail` was logging directly in their package, but I've removed it.

**Closed by snorecone** 2016-11-23 19:19 UTC
